require('dotenv').config();
const express=require('express');
const cors=require('cors');
const multer=require('multer');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const {createClient}=require('@supabase/supabase-js');

const app=express();
const PORT=process.env.PORT||3000;
const ADMIN_KEY=process.env.ADMIN_KEY||'change-me-now';
const ROOT=__dirname, DATA=path.join(ROOT,'data'), UPLOADS=path.join(ROOT,'uploads'), PUBLIC=path.join(ROOT,'public');
for(const d of [DATA,UPLOADS,path.join(PUBLIC,'images','products')])if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
const db=!!pool;
const supabase=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}}):null;
const MEDIA_BUCKET=process.env.SUPABASE_STORAGE_BUCKET||'naile-media';
const file=n=>path.join(DATA,n), read=n=>JSON.parse(fs.readFileSync(file(n),'utf8')), write=(n,v)=>fs.writeFileSync(file(n),JSON.stringify(v,null,2));
for(const n of ['users.json','sessions.json','orders.json','products.json','custom_requests.json'])if(!fs.existsSync(file(n)))write(n,[]);
const id=p=>p+'_'+crypto.randomBytes(5).toString('hex');
const hashPassword=(password,salt=crypto.randomBytes(16).toString('hex'))=>salt+':'+crypto.scryptSync(password,salt,64).toString('hex');
function verifyPassword(password,stored){try{const [salt,hash]=stored.split(':');const a=crypto.scryptSync(password,salt,64);const b=Buffer.from(hash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
async function q(text,params=[]){if(!pool)throw new Error('DATABASE_URL is not configured');return pool.query(text,params)}
const isDb=()=>!!pool;
async function uploadMediaToSupabase(localPath,folder,mimeType){
  if(!supabase)return null;
  const name=path.basename(localPath);
  const objectPath=folder+'/'+name;
  const data=fs.readFileSync(localPath);
  const up=await supabase.storage.from(MEDIA_BUCKET).upload(objectPath,data,{contentType:mimeType||'application/octet-stream',upsert:true});
  if(up.error)throw up.error;
  const pub=supabase.storage.from(MEDIA_BUCKET).getPublicUrl(objectPath);
  return pub.data.publicUrl;
}
async function ensureSupabaseBucket(){
  if(!supabase)return;
  try{const r=await supabase.storage.getBucket(MEDIA_BUCKET);if(!r.data){await supabase.storage.createBucket(MEDIA_BUCKET,{public:true,fileSizeLimit:8388608});}}catch(e){console.warn('Supabase bucket check:',e.message)}
}
ensureSupabaseBucket();

app.use(cors());
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true}));
app.use('/uploads',express.static(UPLOADS));
app.use(express.static(PUBLIC));

const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,UPLOADS),filename:(req,file,cb)=>cb(null,Date.now()+'_'+crypto.randomBytes(4).toString('hex')+path.extname(file.originalname).toLowerCase())});
const upload=multer({storage,limits:{files:5,fileSize:8*1024*1024},fileFilter:(req,f,cb)=>cb(null,/^image\/(jpeg|png|webp)$/.test(f.mimetype))});
const productStorage=multer.diskStorage({destination:(req,file,cb)=>cb(null,path.join(PUBLIC,'images','products')),filename:(req,file,cb)=>{const base=path.basename(file.originalname,path.extname(file.originalname)).toLowerCase().replace(/[^a-z0-9-_]+/g,'-').replace(/^-+|-+$/g,'')||'product';cb(null,base+'_'+Date.now()+path.extname(file.originalname).toLowerCase())}});
const productUpload=multer({storage:productStorage,limits:{files:1,fileSize:8*1024*1024},fileFilter:(req,f,cb)=>cb(null,/^image\/(jpeg|png|webp)$/.test(f.mimetype))});

function admin(req,res,next){if(req.headers['x-admin-key']!==ADMIN_KEY)return res.status(401).json({error:'Unauthorized'});next()}
async function authUser(req){const token=req.headers.authorization?.replace(/^Bearer\s+/,'');if(!token)return null;if(db){const r=await q('SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1',[token]);return r.rows[0]||null}const s=read('sessions.json').find(x=>x.token===token);return s?read('users.json').find(x=>x.id===s.userId)||null:null}
async function customerAuth(req,res,next){try{const u=await authUser(req);if(!u)return res.status(401).json({error:'Login required'});req.user=u;next()}catch(e){res.status(500).json({error:'Auth error'})}}

app.get('/api/health',async(req,res)=>{let database='disabled';if(pool){try{await q('SELECT 1');database='ok'}catch(e){database='error'}}res.json({ok:true,database,mode:db?'postgresql':'json-fallback',storage:supabase?'supabase':'local',midtransConfigured:!!process.env.MIDTRANS_SERVER_KEY,time:new Date().toISOString()})});

app.get('/api/products',async(req,res)=>{try{if(db){const r=await q('SELECT id,name,price,category,emoji,image_url,stock,description FROM products ORDER BY created_at ASC');return res.json(r.rows.map(p=>({...p,price:Number(p.price)})))}res.json(read('products.json'))}catch(e){res.status(500).json({error:'Gagal memuat produk'})}});

app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body||{};if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Nama, email dan password minimal 6 karakter wajib diisi'});const em=String(email).toLowerCase();if(db){const exists=await q('SELECT 1 FROM users WHERE email=$1',[em]);if(exists.rowCount)return res.status(409).json({error:'Email sudah terdaftar'});const user={id:id('USR'),name,email:em,passwordHash:hashPassword(password)};await q('INSERT INTO users(id,name,email,password_hash) VALUES($1,$2,$3,$4)',[user.id,user.name,user.email,user.passwordHash]);const token=crypto.randomBytes(32).toString('hex');await q('INSERT INTO sessions(token,user_id) VALUES($1,$2)',[token,user.id]);return res.status(201).json({token,user:{id:user.id,name:user.name,email:user.email}})}const users=read('users.json');if(users.some(x=>x.email===em))return res.status(409).json({error:'Email sudah terdaftar'});const user={id:id('USR'),name,email:em,passwordHash:hashPassword(password),createdAt:new Date().toISOString()};users.push(user);write('users.json',users);const token=crypto.randomBytes(32).toString('hex');const sessions=read('sessions.json');sessions.push({token,userId:user.id,createdAt:new Date().toISOString()});write('sessions.json',sessions);res.status(201).json({token,user:{id:user.id,name:user.name,email:user.email}})}catch(e){res.status(500).json({error:'Gagal membuat akun'})}});

app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body||{},em=String(email||'').toLowerCase();let user;if(db){const r=await q('SELECT id,name,email,password_hash FROM users WHERE email=$1',[em]);user=r.rows[0];if(!user||!verifyPassword(password||'',user.password_hash))return res.status(401).json({error:'Email atau password salah'});const token=crypto.randomBytes(32).toString('hex');await q('INSERT INTO sessions(token,user_id) VALUES($1,$2)',[token,user.id]);return res.json({token,user:{id:user.id,name:user.name,email:user.email}})}const users=read('users.json');user=users.find(x=>x.email===em);if(!user||!verifyPassword(password||'',user.passwordHash))return res.status(401).json({error:'Email atau password salah'});const token=crypto.randomBytes(32).toString('hex');const sessions=read('sessions.json');sessions.push({token,userId:user.id,createdAt:new Date().toISOString()});write('sessions.json',sessions);res.json({token,user:{id:user.id,name:user.name,email:user.email}})}catch(e){res.status(500).json({error:'Gagal login'})}});
app.get('/api/auth/me',customerAuth,(req,res)=>res.json({user:req.user}));
app.post('/api/auth/logout',customerAuth,async(req,res)=>{try{const token=req.headers.authorization.replace(/^Bearer\s+/,'');if(db)await q('DELETE FROM sessions WHERE token=$1',[token]);else write('sessions.json',read('sessions.json').filter(x=>x.token!==token));res.json({ok:true})}catch(e){res.status(500).json({error:'Gagal logout'})}});

async function getProductsByIds(items,client=null){if(db){const ids=items.map(x=>x.productId);const r=await (client||pool).query('SELECT id,name,price,stock FROM products WHERE id=ANY($1::text[])',[ids]);return r.rows}return read('products.json').filter(p=>items.some(x=>x.productId===p.id))}

app.post('/api/orders',customerAuth,async(req,res)=>{
 const {customer,items,address,paymentMethod='midtrans'}=req.body||{};
 if(!customer?.name||!customer?.contact||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Data order belum lengkap'});
 if(db){const client=await pool.connect();try{await client.query('BEGIN');const products=await getProductsByIds(items,client);let total=0,normalized=[];for(const item of items){const p=products.find(x=>x.id===item.productId);const qty=Math.max(1,Number(item.qty||1));if(!p)throw new Error('PRODUCT_NOT_FOUND');if(qty>p.stock)throw new Error('STOCK_'+p.name);total+=Number(p.price)*qty;normalized.push({productId:p.id,name:p.name,price:Number(p.price),qty})}const orderId=id('ORD');await client.query(`INSERT INTO orders(id,user_id,status,payment_status,payment_provider,customer_name,customer_contact,address,total,payment_method) VALUES($1,$2,'pending_payment','pending','midtrans',$3,$4,$5,$6,$7)`,[orderId,req.user.id,customer.name,customer.contact,address||'',total,paymentMethod]);for(const it of normalized){await client.query('INSERT INTO order_items(order_id,product_id,product_name,price,qty) VALUES($1,$2,$3,$4,$5)',[orderId,it.productId,it.name,it.price,it.qty]);await client.query('UPDATE products SET stock=stock-$1,updated_at=now() WHERE id=$2',[it.qty,it.productId])}await client.query('COMMIT');return res.status(201).json({id:orderId,status:'pending_payment',paymentStatus:'pending',total,items:normalized})}catch(e){await client.query('ROLLBACK');console.error(e);if(e.message==='PRODUCT_NOT_FOUND')return res.status(400).json({error:'Produk tidak ditemukan'});if(e.message.startsWith('STOCK_'))return res.status(400).json({error:`Stok ${e.message.slice(6)} tidak mencukupi`});res.status(500).json({error:'Gagal membuat order'})}finally{client.release()}return}
 const products=read('products.json');let total=0,normalized=[];for(const item of items){const p=products.find(x=>x.id===item.productId),qty=Math.max(1,Number(item.qty||1));if(!p)return res.status(400).json({error:'Produk tidak ditemukan'});if(qty>p.stock)return res.status(400).json({error:`Stok ${p.name} tidak mencukupi`});total+=p.price*qty;normalized.push({productId:p.id,name:p.name,price:p.price,qty});}const orders=read('orders.json');const order={id:id('ORD'),createdAt:new Date().toISOString(),status:'pending_payment',paymentStatus:'pending',customer,items:normalized,total,address:address||'',paymentMethod,userId:req.user.id,stockReleased:false};orders.unshift(order);write('orders.json',orders);normalized.forEach(it=>{const p=products.find(x=>x.id===it.productId);p.stock-=it.qty});write('products.json',products);res.status(201).json(order);
});

async function getOrder(orderId,userId){if(db){const r=await q(`SELECT o.*,COALESCE(json_agg(json_build_object('productId',oi.product_id,'name',oi.product_name,'price',oi.price,'qty',oi.qty) ORDER BY oi.id) FILTER (WHERE oi.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id WHERE o.id=$1 AND o.user_id=$2 GROUP BY o.id`,[orderId,userId]);if(!r.rows[0])return null;const o=r.rows[0];return {...o,total:Number(o.total),items:o.items.map(x=>({...x,price:Number(x.price)})),paymentStatus:o.payment_status}}return read('orders.json').find(x=>x.id===orderId&&x.userId===userId)||null}

app.get('/api/my/orders',customerAuth,async(req,res)=>{try{if(db){const r=await q(`SELECT o.*,COALESCE(json_agg(json_build_object('productId',oi.product_id,'name',oi.product_name,'price',oi.price,'qty',oi.qty) ORDER BY oi.id) FILTER (WHERE oi.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id WHERE o.user_id=$1 GROUP BY o.id ORDER BY o.created_at DESC`,[req.user.id]);return res.json(r.rows.map(o=>({...o,total:Number(o.total),items:o.items.map(x=>({...x,price:Number(x.price)})),paymentStatus:o.payment_status})))}res.json(read('orders.json').filter(x=>x.userId===req.user.id))}catch(e){console.error(e);res.status(500).json({error:'Gagal memuat order'})}});

function midtransBase(){return process.env.MIDTRANS_IS_PRODUCTION==='true'?'https://app.midtrans.com':'https://app.sandbox.midtrans.com'}
function midtransClientBase(){return process.env.MIDTRANS_IS_PRODUCTION==='true'?'https://app.midtrans.com':'https://app.sandbox.midtrans.com'}
app.get('/api/payments/config',(req,res)=>res.json({enabled:!!process.env.MIDTRANS_CLIENT_KEY,clientKey:process.env.MIDTRANS_CLIENT_KEY||'',production:process.env.MIDTRANS_IS_PRODUCTION==='true'}));
app.post('/api/payments/midtrans',customerAuth,async(req,res)=>{const {orderId}=req.body||{};try{const order=await getOrder(orderId,req.user.id);if(!order)return res.status(404).json({error:'Order tidak ditemukan'});if(order.status!=='pending_payment'||order.paymentStatus==='paid')return res.status(400).json({error:'Order tidak dapat dibayar lagi'});if(!process.env.MIDTRANS_SERVER_KEY||!process.env.MIDTRANS_CLIENT_KEY)return res.status(503).json({error:'MIDTRANS_SERVER_KEY dan MIDTRANS_CLIENT_KEY belum dikonfigurasi'});const auth=Buffer.from(process.env.MIDTRANS_SERVER_KEY+':').toString('base64');const r=await fetch(midtransBase()+'/snap/v1/transactions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Basic '+auth},body:JSON.stringify({transaction_details:{order_id:order.id,gross_amount:Number(order.total)},customer_details:{first_name:order.customer_name||order.customer?.name,email:order.customer_contact||order.customer?.contact},callbacks:{finish:process.env.MIDTRANS_FINISH_URL||'/'}})});const d=await r.json();if(!r.ok)return res.status(502).json({error:d.status_message||'Midtrans error'});res.json({token:d.token,redirect_url:d.redirect_url})}catch(e){console.error(e);res.status(502).json({error:'Payment gateway tidak dapat dihubungi'})}});

async function restoreStock(orderId){if(db){const client=await pool.connect();try{await client.query('BEGIN');const o=await client.query('SELECT stock_released FROM orders WHERE id=$1 FOR UPDATE',[orderId]);if(!o.rows[0]||o.rows[0].stock_released){await client.query('COMMIT');return}const its=await client.query('SELECT product_id,qty FROM order_items WHERE order_id=$1',[orderId]);for(const it of its.rows)await client.query('UPDATE products SET stock=stock+$1,updated_at=now() WHERE id=$2',[it.qty,it.product_id]);await client.query('UPDATE orders SET stock_released=true,updated_at=now() WHERE id=$1',[orderId]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}else{const orders=read('orders.json'),i=orders.findIndex(x=>x.id===orderId);if(i<0||orders[i].stockReleased)return;const products=read('products.json');for(const it of orders[i].items){const p=products.find(x=>x.id===it.productId);if(p)p.stock+=it.qty}orders[i].stockReleased=true;write('products.json',products);write('orders.json',orders)}}

function verifyMidtrans(n){const raw=String(n.order_id||'')+String(n.status_code||'')+String(n.gross_amount||'')+String(process.env.MIDTRANS_SERVER_KEY||'');const expected=crypto.createHash('sha512').update(raw).digest('hex');return expected===String(n.signature_key||'')}
app.post('/api/payments/midtrans/webhook',async(req,res)=>{const n=req.body||{};if(!n.order_id)return res.status(400).json({error:'Missing order_id'});if(!process.env.MIDTRANS_SERVER_KEY)return res.status(503).json({error:'MIDTRANS_SERVER_KEY belum dikonfigurasi'});if(!verifyMidtrans(n))return res.status(401).json({error:'Invalid signature'});let paymentStatus='pending',status='pending_payment';const t=n.transaction_status, fraud=n.fraud_status;if(t==='capture'){paymentStatus=fraud==='challenge'?'challenge':'paid';status=paymentStatus==='paid'?'paid':'pending_payment'}else if(t==='settlement'){paymentStatus='paid';status='paid'}else if(t==='pending'){paymentStatus='pending';status='pending_payment'}else if(['deny','cancel','expire','failure'].includes(t)){paymentStatus=t==='expire'?'expired':'failed';status='cancelled'}try{if(db){const current=await q('SELECT payment_status,status FROM orders WHERE id=$1',[n.order_id]);if(current.rowCount&&current.rows[0].payment_status==='paid'&&status==='cancelled')return res.json({ok:true,ignored:true});await q(`UPDATE orders SET payment_status=$1,status=$2,payment_transaction_id=$3,updated_at=now() WHERE id=$4`,[paymentStatus,status,n.transaction_id||null,n.order_id]);if(status==='cancelled')await restoreStock(n.order_id)}else{const orders=read('orders.json'),i=orders.findIndex(x=>x.id===n.order_id);if(i>=0){orders[i].paymentStatus=paymentStatus;orders[i].status=status;orders[i].paymentTransactionId=n.transaction_id||null;write('orders.json',orders);if(status==='cancelled')await restoreStock(n.order_id)}}res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Webhook processing failed'})}});

app.get('/api/orders',admin,async(req,res)=>{try{if(db){const r=await q(`SELECT o.*,COALESCE(json_agg(json_build_object('productId',oi.product_id,'name',oi.product_name,'price',oi.price,'qty',oi.qty) ORDER BY oi.id) FILTER (WHERE oi.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id GROUP BY o.id ORDER BY o.created_at DESC`);return res.json(r.rows.map(o=>({...o,total:Number(o.total),items:o.items.map(x=>({...x,price:Number(x.price)})),paymentStatus:o.payment_status})))}res.json(read('orders.json'))}catch(e){res.status(500).json({error:'Gagal memuat order'})}});
app.patch('/api/orders/:id',admin,async(req,res)=>{const st=req.body.status;if(!st)return res.status(400).json({error:'Status wajib'});try{if(db){const r=await q('UPDATE orders SET status=$1,updated_at=now() WHERE id=$2 RETURNING *',[st,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Order tidak ditemukan'});return res.json(r.rows[0])}const a=read('orders.json'),i=a.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Order tidak ditemukan'});a[i].status=st;write('orders.json',a);res.json(a[i])}catch(e){res.status(500).json({error:'Gagal update order'})}});

app.post('/api/custom-requests',upload.array('references',5),async(req,res)=>{try{const b=req.body||{};if(!b.name||!b.contact)return res.status(400).json({error:'Nama dan kontak wajib diisi'});let sizes={};try{sizes=JSON.parse(b.sizes||'{}')}catch{}let refs=[];
 for(const f of (req.files||[])){
   if(supabase){try{const url=await uploadMediaToSupabase(f.path,'custom-references',f.mimetype);refs.push(url);fs.unlinkSync(f.path)}catch(e){console.error('Supabase reference upload failed:',e.message);refs.push('/uploads/'+f.filename)}}
   else refs.push('/uploads/'+f.filename);
 }if(db){const r=await q(`INSERT INTO custom_requests(id,user_id,status,name,contact,shape,notes,sizes,references) VALUES($1,$2,'new',$3,$4,$5,$6,$7,$8) RETURNING *`,[id('CUS'),(await authUser(req))?.id||null,b.name,b.contact,b.shape||'Almond',b.notes||'',sizes,JSON.stringify(refs)]);return res.status(201).json(r.rows[0])}const rows=read('custom_requests.json'),item={id:id('CUS'),createdAt:new Date().toISOString(),status:'new',name:b.name,contact:b.contact,shape:b.shape||'Almond',notes:b.notes||'',sizes,references:refs,userId:(await authUser(req))?.id||null};rows.unshift(item);write('custom_requests.json',rows);res.status(201).json(item)}catch(e){console.error(e);res.status(500).json({error:'Gagal mengirim custom request'})}});
app.get('/api/custom-requests',admin,async(req,res)=>{try{if(db){const r=await q('SELECT * FROM custom_requests ORDER BY created_at DESC');return res.json(r.rows)}res.json(read('custom_requests.json'))}catch(e){res.status(500).json({error:'Gagal memuat custom request'})}});
app.patch('/api/custom-requests/:id',admin,async(req,res)=>{try{if(db){const allowed=['status','quoted_price','notes'];const sets=[],vals=[];for(const k of allowed)if(req.body[k]!==undefined){sets.push(k+'=$'+(vals.length+1));vals.push(req.body[k])}if(!sets.length)return res.status(400).json({error:'Tidak ada perubahan'});vals.push(req.params.id);const r=await q('UPDATE custom_requests SET '+sets.join(',')+',updated_at=now() WHERE id=$'+vals.length+' RETURNING *',vals);if(!r.rowCount)return res.status(404).json({error:'Request tidak ditemukan'});return res.json(r.rows[0])}const rows=read('custom_requests.json'),i=rows.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Request tidak ditemukan'});Object.assign(rows[i],req.body);write('custom_requests.json',rows);res.json(rows[i])}catch(e){res.status(500).json({error:'Gagal update custom request'})}});

app.get('/api/admin/summary',admin,async(req,res)=>{try{if(db){const [o,c,u,rev]=await Promise.all([q("SELECT COUNT(*)::int n FROM orders"),q("SELECT COUNT(*)::int n FROM custom_requests WHERE status='new'"),q('SELECT COUNT(*)::int n FROM users'),q("SELECT COALESCE(SUM(total),0)::numeric n FROM orders WHERE payment_status='paid'")]);return res.json({orders:o.rows[0].n,pending:(await q("SELECT COUNT(*)::int n FROM orders WHERE status='pending_payment'")).rows[0].n,custom:c.rows[0].n,customers:u.rows[0].n,revenue:Number(rev.rows[0].n)})}const orders=read('orders.json'),custom=read('custom_requests.json');res.json({orders:orders.length,pending:orders.filter(x=>x.status==='pending_payment').length,custom:custom.filter(x=>x.status==='new').length,customers:read('users.json').length,revenue:orders.filter(x=>x.paymentStatus==='paid').reduce((s,x)=>s+x.total,0)})}catch(e){res.status(500).json({error:'Gagal memuat summary'})}});

app.post('/api/products/upload-image',admin,productUpload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'File gambar wajib diisi'});if(supabase){const url=await uploadMediaToSupabase(req.file.path,'products',req.file.mimetype);fs.unlinkSync(req.file.path);return res.status(201).json({url,filename:req.file.filename,storage:'supabase'})}res.status(201).json({url:'/images/products/'+req.file.filename,filename:req.file.filename,storage:'local'})}catch(e){console.error(e);res.status(500).json({error:'Gagal upload gambar'})}});

app.post('/api/products',admin,async(req,res)=>{const {name,price,category='Soft',emoji='💅🏻',imageUrl=null,stock=0,description=''}=req.body||{};if(!name||Number(price)<0)return res.status(400).json({error:'Nama dan harga wajib'});try{const p={id:id('N'),name,price:Number(price),category,emoji,imageUrl,stock:Number(stock)||0,description};if(db){const r=await q('INSERT INTO products(id,name,price,category,emoji,image_url,stock,description) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[p.id,p.name,p.price,p.category,p.emoji,p.imageUrl,p.stock,p.description]);return res.status(201).json({...r.rows[0],price:Number(r.rows[0].price)})}const a=read('products.json');a.push({...p,image:p.imageUrl});write('products.json',a);res.status(201).json(p)}catch(e){res.status(500).json({error:'Gagal menambah produk'})}});
app.patch('/api/products/:id',admin,async(req,res)=>{try{const fields=['name','price','category','emoji','imageUrl','stock','description'];if(db){const sets=[],vals=[];for(const k of fields)if(req.body[k]!==undefined){sets.push((k==='imageUrl'?'image_url':k)+'=$'+(vals.length+1));vals.push(k==='price'||k==='stock'?Number(req.body[k]):req.body[k])}if(!sets.length)return res.status(400).json({error:'Tidak ada perubahan'});vals.push(req.params.id);const r=await q('UPDATE products SET '+sets.join(',')+',updated_at=now() WHERE id=$'+vals.length+' RETURNING *',vals);if(!r.rowCount)return res.status(404).json({error:'Produk tidak ditemukan'});return res.json({...r.rows[0],price:Number(r.rows[0].price)})}const a=read('products.json'),i=a.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Produk tidak ditemukan'});for(const k of fields)if(req.body[k]!==undefined)a[i][k]=k==='price'||k==='stock'?Number(req.body[k]):req.body[k];write('products.json',a);res.json(a[i])}catch(e){res.status(500).json({error:'Gagal update produk'})}});
app.delete('/api/products/:id',admin,async(req,res)=>{try{if(db){const r=await q('DELETE FROM products WHERE id=$1 RETURNING id',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Produk tidak ditemukan'});return res.json({ok:true})}const a=read('products.json'),n=a.filter(x=>x.id!==req.params.id);if(n.length===a.length)return res.status(404).json({error:'Produk tidak ditemukan'});write('products.json',n);res.json({ok:true})}catch(e){res.status(500).json({error:'Gagal hapus produk'})}});

app.get(/^\/(?!api(?:\/|$)).*/,(req,res)=>res.sendFile(path.join(PUBLIC,'index.html')));
app.listen(PORT,()=>console.log(`NAILÉ running on http://localhost:${PORT} | mode=${db?'PostgreSQL':'JSON fallback'}`));
